### ISSUE TITLE
Daemon mode to speed up startup

### ISSUE THREAD

**Issue by seeM** [fastai/execnb#18]
There've been ongoing discussions in various channels about adding a daemon mode to `execnb`. Although this is probably a longer-term thing, I thought an issue could be a good place to store useful notes and important decisions made along the way.

#### What is a daemon mode?

@jph00's [thread](https://twitter.com/jeremyphoward/status/1534999290027778048) sums it up well:

> Python scripts can be slow to start because the imports can take a long time. I have lots of scripts that read/write stdin/out. I'd like to replace them with something with identical behavior, but which behind the scenes auto-launches a little server.
> [...]
> The idea is that the overhead of starting the script only happens once. This is useful for stuff like git hook scripts.

#### References

- [PEP 3143 – Standard daemon process library](https://peps.python.org/pep-3143/)
- [`python-daemon`](https://pypi.org/project/python-daemon/): reference implementation for PEP 3143
- [Rules that daemons are meant to follow](https://software.clapper.org/daemonize/)
- [`daemonize`](https://github.com/thesharp/daemonize/): a library for writing system daemons in Python (unmaintained)
- [Discussion on a daemon mode for Python](https://github.com/faster-cpython/ideas/discussions/129)

cc @hamelsmu

**Comment by jph00** [comment]
I think we don't need this anymore since we have a parallel filter in nbdev now.
