### ISSUE TITLE
How fast is it?

### ISSUE THREAD

**Issue by pplonski** [fastai/execnb#36]
Is there any speed comparison with `nbconvert`?

Is it possible to use `execnb` with an already running kernel?

I'm working on a tool for converting Jupyter Notebook to interactive Web Apps - to make notebooks accessible for non-technical users. The tool is called [Mercury](https://github.com/mljar/mercury). You can add widgets to the notebook by simply adding a YAML header in the first cell. The framework is based on `nbconvert`. I would love to use a faster tool for executing notebooks.

**Comment by jph00** [comment]
The overhead is close to zero. So if you've doing a small amount of stuff in your kernel then the speedup will be dramatic.

If you give it a go, please let us know how you get along, and feel free to ask anything in issues here - at-mention me so I don't miss it.
