### ISSUE TITLE
should I close `CaptureShell`?

### ISSUE THREAD

**Issue by pplonski** [fastai/execnb#45]
When I initialize `CaptureShell()`, I have an interactive shell running, should I close it somehow after computation?

I was experimenting with `CaptureShell` by creating hundreds of shells, and the RAM usage didn't increase a lot, I was expecting that each shell would need ~200MB RAM. Why was RAM usage so low?

I started to work on V2 for [Mercury](https://github.com/mljar/mercury) framework (converting notebook to apps) and using `execnb` as execution engine.

**Comment by pplonski** [comment]
Thanks @jph00! I'm using `execnb` as a core execution engine in Mercury framework. It turns Jupyter Notebook into interactive web app, slides, websites, and dashboards. This month I will release Mercury V2, which is ~ x20 faster than V1 thanks to `execnb` (in the previous version I was starting a new Python kernel for each request). 

Mercury repo: https://github.com/mljar/mercury
Mercury docs: [RunMercury.com](https://RunMercury.com)

**Comment by jph00** [comment]
That's very exciting @pplonski ! :D Feel free to at-mention me on any issues/bugs/questions that come up along the way. AFAIK execnb usage has largely been restricted to nbdev so far, so it's good to see it being exercised more widely.
