### ISSUE TITLE
[Feature request] Running multiple notebooks from the command line

### ISSUE THREAD

**Issue by aditya-283** [fastai/execnb#47]
Wondering if it's possible to accept multiple notebook sources as arguments to the command line tool.
e.g. `exec_nb nb1.ipynb nb2.ipynb --exc_stop` 

Still need the `--exc_stop` option to stop if any notebook raises an exception in any cell.

This enables the use of notebooks as testable documentation that can be integrated with other tools like CMake. Currently, the way to do that would be to write a shell script that iterates over said notebooks and calls `exec_nb` one by one.

**Comment by hamelsmu** [comment]
@aditya-283 Let's try to use [nbdev_test](https://nbdev.fast.ai/tutorials/modular_nbdev.html#testing-notebooks-nbdev_test)
